FROM rust:1.70 as builder

WORKDIR /usr/src/portal

COPY . .

RUN set -x && \
    NODEJS_VERSION=v16.17.0 && \
    curl -O -L https://registry.npmmirror.com/-/binary/node/latest-v16.x/node-$NODEJS_VERSION-linux-x64.tar.gz && \
    tar zxf node-$NODEJS_VERSION-linux-x64.tar.gz && \
    rm node-$NODEJS_VERSION-linux-x64.tar.gz && \
    mv node-$NODEJS_VERSION-linux-x64/ /nodejs && \
    PATH=$PATH:/nodejs/bin && \
    npm config set registry https://registry.npmmirror.com && \
    npm i tailwindcss -g && \
    CARGO_HOME=/usr/src/portal/cargo_home && \
    mkdir -p $CARGO_HOME && \
    echo "[source.crates-io]\nreplace-with = 'ustc'\n[source.ustc]\nregistry = 'git://mirrors.ustc.edu.cn/crates.io-index'" > $CARGO_HOME/config && \
    export CARGO_HOME && \
    # build client
    cd /usr/src/portal/client && rustup target add wasm32-unknown-unknown && cargo install trunk --version 0.16.0 && trunk build --release

FROM nginx

WORKDIR /usr/src/client

COPY --from=builder /usr/src/portal/client/dist /usr/share/nginx/html/

RUN echo "Asia/Shanghai" > /etc/timezone

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

COPY client/nginx.dev.conf /etc/nginx/nginx.conf

EXPOSE 8080/tcp

CMD ["nginx", "-g", "daemon off;"]