package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	"fmt"

	"github.com/TsaoLun/portal/fiber-server/graph/model"
)

// Set is the resolver for the set field.
func (r *mutationResolver) Set(ctx context.Context, data string) (bool, error) {
	panic(fmt.Errorf("not implemented: Set - set"))
}

// Get is the resolver for the get field.
func (r *queryResolver) Get(ctx context.Context) (string, error) {
	panic(fmt.Errorf("not implemented: Get - get"))
}

// Login is the resolver for the login field.
func (r *queryResolver) Login(ctx context.Context, username string, password string) (*model.TokenResponse, error) {
	panic(fmt.Errorf("not implemented: Login - login"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
