// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type TokenResponse struct {
	Ok    bool    `json:"ok"`
	Token *string `json:"token,omitempty"`
}
